use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

#[path = "shared/media_manifest.rs"]
mod media_manifest;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing manifest dir"));
    let project_root = manifest_dir.as_path();
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));
    let platformio_home = platformio_packages_dir();
    let gcc = platformio_home.join("toolchain-gccarmnoneeabi/bin/arm-none-eabi-gcc");
    let ar = platformio_home.join("toolchain-gccarmnoneeabi/bin/arm-none-eabi-ar");
    let cmsis_core = platformio_home.join("framework-cmsis/CMSIS/Core/Include");
    let cmsis_device = platformio_home.join("framework-cmsis-stm32f4/Include");

    println!("cargo:rerun-if-changed=memory.x");
    println!("cargo:rerun-if-changed=c_support/clock/hardware_system_init.c");
    println!("cargo:rerun-if-changed=c_support/tft");
    println!("cargo:rerun-if-env-changed=PLATFORMIO_PACKAGES_DIR");
    println!("cargo:rerun-if-env-changed=MINIOS_EMBED_ALBUM");
    println!("cargo:rustc-check-cfg=cfg(minios_mac_companion)");
    println!("cargo:rustc-link-search={}", project_root.display());
    println!(
        "cargo:rerun-if-changed={}",
        project_root.join("assets/test_media/converted").display()
    );

    let embed_album_media = embed_album_media();
    if !embed_album_media {
        println!("cargo:rustc-cfg=minios_mac_companion");
    }
    let (still_count, clip_count) =
        generate_media_module(project_root, &out_dir, embed_album_media);
    emit_build_metadata(project_root, still_count, clip_count, embed_album_media);

    let common = |build: &mut cc::Build| {
        build
            .compiler(&gcc)
            .archiver(&ar)
            .include(project_root.join("c_support/tft/include"))
            .include(project_root.join("c_support/clock"))
            .include(&cmsis_core)
            .include(&cmsis_device)
            .flag("-mcpu=cortex-m4")
            .flag("-mthumb")
            .flag("-mfpu=fpv4-sp-d16")
            .flag("-mfloat-abi=hard")
            .flag("-ffunction-sections")
            .flag("-fdata-sections")
            .flag("-fno-builtin")
            .flag("-std=gnu11")
            .flag("-Wno-comment")
            .flag_if_supported("-Wno-old-style-declaration")
            .flag_if_supported("-Wno-maybe-uninitialized")
            .define("STM32F407xx", None)
            .define("HSE_VALUE", Some("8000000U"));
    };

    let mut board_support = cc::Build::new();
    common(&mut board_support);
    board_support.file(project_root.join("c_support/clock/hardware_system_init.c"));
    board_support.compile("board_support");

    let mut tft = cc::Build::new();
    common(&mut tft);
    for file in [
        "c_support/tft/src/stm324xg_lcd_ILI9341_Pro.c",
        "c_support/tft/src/stm32f4xx_fsmc.c",
        "c_support/tft/src/Fonts/font8.c",
        "c_support/tft/src/Fonts/font12.c",
        "c_support/tft/src/Fonts/font16.c",
        "c_support/tft/src/Fonts/font20.c",
        "c_support/tft/src/Fonts/font24.c",
        "c_support/tft/src/Fonts/fonts_16x24.c",
        "c_support/tft/src/Fonts/fonts_hz.c",
    ] {
        tft.file(project_root.join(file));
    }
    tft.compile("tft_support");
}

fn embed_album_media() -> bool {
    env::var("MINIOS_EMBED_ALBUM")
        .ok()
        .map(|value| !matches!(value.as_str(), "0" | "false" | "FALSE" | "no" | "NO"))
        .unwrap_or(true)
}

fn platformio_packages_dir() -> PathBuf {
    if let Ok(path) = env::var("PLATFORMIO_PACKAGES_DIR") {
        return PathBuf::from(path);
    }

    let home = env::var("HOME").expect("missing HOME environment variable");
    Path::new(&home).join(".platformio/packages")
}

fn generate_media_module(
    project_root: &Path,
    out_dir: &Path,
    embed_album_media: bool,
) -> (usize, usize) {
    let converted_root = project_root.join("assets/test_media/converted");
    let firmware_root = converted_root.join("firmware");
    let stills_root = firmware_root.join("stills");
    let motion_root = firmware_root.join("motion");
    let manifests_root = converted_root.join("manifests");

    let mut output = String::new();
    output.push_str("// @generated by build.rs\n");
    output.push_str("// Do not edit by hand.\n\n");

    let stills = if embed_album_media {
        media_manifest::collect_stills(&stills_root, &manifests_root)
    } else {
        Vec::new()
    };
    let still_count = stills.len();
    output.push_str(&format!(
        "pub static STILL_IMAGES: [EmbeddedStill; {}] = [\n",
        stills.len()
    ));
    for still in stills {
        output.push_str(&format!(
            "    EmbeddedStill {{ label: {:?}, width: {}, height: {}, scale: {}, data: include_bytes!(r#\"{}\"#) }},\n",
            still.label,
            still.width,
            still.height,
            still.scale,
            still.path.display()
        ));
    }
    output.push_str("];\n\n");

    let clips = if embed_album_media {
        media_manifest::collect_motion_clips(&motion_root, &manifests_root)
    } else {
        Vec::new()
    };
    let clip_count = clips.len();
    for clip in &clips {
        output.push_str(&format!(
            "static {}: [&[u8]; {}] = [\n",
            clip.symbol,
            clip.frames.len()
        ));
        for frame in &clip.frames {
            output.push_str(&format!(
                "    include_bytes!(r#\"{}\"#),\n",
                frame.display()
            ));
        }
        output.push_str("];\n\n");
    }

    output.push_str(&format!(
        "pub static MOTION_CLIPS: [EmbeddedMotionClip; {}] = [\n",
        clips.len()
    ));
    for clip in clips {
        output.push_str(&format!(
            "    EmbeddedMotionClip {{ label: {:?}, width: {}, height: {}, scale: {}, frame_delay_ms: {}, frames: &{} }},\n",
            clip.label,
            clip.width,
            clip.height,
            clip.scale,
            clip.frame_delay_ms,
            clip.symbol
        ));
    }
    output.push_str("];\n");

    let output_path = out_dir.join("generated_media.rs");
    fs::write(output_path, output).expect("failed to write generated media module");
    (still_count, clip_count)
}

fn emit_build_metadata(
    project_root: &Path,
    still_count: usize,
    clip_count: usize,
    embed_album_media: bool,
) {
    println!(
        "cargo:rustc-env=MINIOS_BUILD_PROFILE={}",
        env::var("PROFILE").unwrap_or_else(|_| "unknown".to_string())
    );
    println!(
        "cargo:rustc-env=MINIOS_BUILD_TARGET={}",
        env::var("TARGET").unwrap_or_else(|_| "unknown-target".to_string())
    );
    println!(
        "cargo:rustc-env=MINIOS_ALBUM_BACKEND={}",
        if embed_album_media {
            "embedded"
        } else {
            "mac-companion"
        }
    );
    println!("cargo:rustc-env=MINIOS_MEDIA_STILLS={still_count}");
    println!("cargo:rustc-env=MINIOS_MEDIA_CLIPS={clip_count}");

    let git_sha = Command::new("git")
        .arg("-C")
        .arg(project_root)
        .arg("rev-parse")
        .arg("--short")
        .arg("HEAD")
        .output()
        .ok()
        .and_then(|output| {
            if output.status.success() {
                String::from_utf8(output.stdout).ok()
            } else {
                None
            }
        })
        .map(|value| value.trim().to_string())
        .filter(|value| !value.is_empty())
        .unwrap_or_else(|| "nogit".to_string());
    println!("cargo:rustc-env=MINIOS_GIT_SHA={git_sha}");
}
