[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
linker = "./tools/arm-gcc.sh"
runner = "./flash.sh"
rustflags = [
  "-C",
  "link-arg=-Tlink.x",
  "-C",
  "link-arg=-Wl,--nmagic",
  "-C",
  "link-arg=-Wl,--gc-sections",
  "-C",
  "link-arg=-mcpu=cortex-m4",
  "-C",
  "link-arg=-mthumb",
  "-C",
  "link-arg=-mfpu=fpv4-sp-d16",
  "-C",
  "link-arg=-mfloat-abi=hard",
]
