from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
SOURCES = [ROOT / "src" / "main.rs", ROOT / "src" / "dungeon.rs"]
OUT = ROOT / "src" / "font_zh.rs"
FONT_PATHS = [
    Path("/System/Library/Fonts/STHeiti Medium.ttc"),
    Path("/System/Library/Fonts/Hiragino Sans GB.ttc"),
    Path("/Library/Fonts/Arial Unicode.ttf"),
]
CANVAS = 12


def load_font() -> ImageFont.FreeTypeFont:
    for path in FONT_PATHS:
        if path.exists():
            return ImageFont.truetype(str(path), 13)
    raise SystemExit("No usable CJK font found on this Mac.")


def collect_chars() -> list[str]:
    chars: set[str] = set()
    for source in SOURCES:
        text = source.read_text(encoding="utf-8")
        chars.update(ch for ch in text if ord(ch) > 127 and not ch.isspace())
    return sorted(chars)


def render_rows(font: ImageFont.FreeTypeFont, ch: str) -> list[int]:
    image = Image.new("L", (CANVAS, CANVAS), 0)
    draw = ImageDraw.Draw(image)
    bbox = draw.textbbox((0, 0), ch, font=font)
    width = bbox[2] - bbox[0]
    height = bbox[3] - bbox[1]
    x = (CANVAS - width) // 2 - bbox[0]
    y = (CANVAS - height) // 2 - bbox[1] - 1
    draw.text((x, y), ch, fill=255, font=font)

    rows: list[int] = []
    for py in range(CANVAS):
        bits = 0
        for px in range(CANVAS):
            if image.getpixel((px, py)) >= 64:
                bits |= 1 << (CANVAS - 1 - px)
        rows.append(bits)
    return rows


def main() -> None:
    font = load_font()
    chars = collect_chars()

    lines = [
        "// @generated by tools/gen_zh_font.py",
        "// Do not edit by hand.",
        "",
        "pub fn glyph(ch: char) -> Option<[u16; 12]> {",
        "    match ch {",
    ]

    for ch in chars:
        rows = render_rows(font, ch)
        row_text = ", ".join(f"0x{row:03X}" for row in rows)
        lines.append(f"        {ch!r} => Some([{row_text}]),")

    lines.extend(
        [
            "        _ => None,",
            "    }",
            "}",
            "",
        ]
    )

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {OUT} with {len(chars)} glyphs.")


if __name__ == "__main__":
    main()
